// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkzVIw4NwJEybsmBj322YQ0HUsMp4MyNc',
    appId: '1:142505763084:web:31697045347ec79f676929',
    messagingSenderId: '142505763084',
    projectId: 'notesapp31-flutter',
    authDomain: 'notesapp31-flutter.firebaseapp.com',
    storageBucket: 'notesapp31-flutter.appspot.com',
    measurementId: 'G-T9XCM0YJ8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ1-xA-_02p0CpRhyyhyKRBcHIo3Q0vkc',
    appId: '1:142505763084:android:00b89e143e1a071d676929',
    messagingSenderId: '142505763084',
    projectId: 'notesapp31-flutter',
    storageBucket: 'notesapp31-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAINmTr3m1S2824ArECPfxKxf-tIUB__c',
    appId: '1:142505763084:ios:22ac8b0070570905676929',
    messagingSenderId: '142505763084',
    projectId: 'notesapp31-flutter',
    storageBucket: 'notesapp31-flutter.appspot.com',
    iosClientId: '142505763084-pft8dt6uf9bctqdl9fn89r9bd4t7cin1.apps.googleusercontent.com',
    iosBundleId: 'com.hello.notesapp',
  );
}
